### PR TITLE
Warning user about possibility of terminal choice

### LINKED ISSUE #56: Warn User about Terminal customization When Exception Occurs
As the titlle says, I think it would be cool to warn user about the terminal settings on errors, instead of showing an exception from the Spawner.

### PR DESCRIPTION
**Pull request by Megamiun**
Hello, changed the error message so the user knows of the terminal settings in case of error.

Oh, and like I said before, english is my second language, so it is possible that the message didn't. Resolves #56.

### CODE REVIEW

File: lib/terminal.js [hunk 1]
```diff
@@ -330,6 +330,15 @@ class SpawnWrapper extends Base {
     tty(model) {
         model.options = this.optionWrapper(model.options);
         let tty = this.spawnWrapper(model);
+        let shellName = this.object.shell;
```
Comment (xovertheyearsx) [inline lib/terminal.js]: This might be better off in the `atom-python-run.js` module considering [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns). Seeing as this is a notification about manipulating the settings. I do understand the appeal of adding this to the `SpawnWrapper.tty()` method. Does it _need_ to be in the `tty()` method? 

I only bring this up because `terminal.js` is meant to be modular and behave as a separate entity from the `atom-python-run.js` module. Adding `atom`s API to the `terminal.js` module makes it difficult to debug on its own since its now dependent up it.

Comment (Megamiun) [reply lib/terminal.js]: Oh, it's true! Didn't think too much of this, was too busy thinking of how to implement, forgot to think about the design and just did a version that always returned it prepared. Probably it would be better to pass the error behaviour as a argument, I think?

Thinking about it, it not only creates a link to atom, it creates a link to the project, as as you said, it is important for it to be reausable independent of atom-python-run, no? I will change it later.

Oh, and talking about it, what did you think about the message? Any changes?

Comment (Megamiun) [reply lib/terminal.js]: Thinking of leaving something like that on the `tty(model)` method:

```javascript
tty.on('error',
    error => model.onError(error, this.object.shell)
)
```
And passing a function like that as a argument to the method:

```javascript
function onError(error, shellName) {
    atom.notifications.addError('There was a problem opening \''
        + shellName + '\'. If your computer doesn\'t have \'' + shellName
        + '\' installed, you can set your own terminal on the package\'s ' +
        'Settings.');
}
```

Maybe you would prefer me passing asking for the object as a whole instead of just the shell name, if who uses the terminal.js wants to use more info to create their error message.

Comment (xovertheyearsx) [reply lib/terminal.js]: > Thinking about it, it not only creates a link to atom, it creates a link to the project, as as you said, it is important for it to be reausable independent of atom-python-run, no?

It's more about being able to debug it than reuse it. Not sure why someone would reuse this code outside of this context. `terminal.js`s job is to create the tty object based on the OS it runs on (if it can) and nothing else. keeping `atom`s API out of the mix keeps it cleaner that way by removing that abstraction from the equation as whole. it's mainly dependent upon `node` more than anything else.

> Oh, and talking about it, what did you think about the message? Any changes?

I like it. It lets the user know why it's not working and seems to have a valid purpose. Keep issues from being opened related to this. The only thing is that it's too quick in my opinion... is there a way to change the duration of the notification? I get a lot of notifications, but they always go by so quick!!! lol >.< its frustrating

> Maybe you would prefer me passing asking for the object as a whole instead of just the shell name, if who uses the terminal.js wants to use more info to create their error message.

I like it. The function is simple and clean and can be called as a method to the `model` object. Which is what it's there for in the first place. Something like

`model.onError` or even `model.onTTYError` or something along those lines. Give it a clear context.

I've noticed that `atom`s API is mainly event driven and the bit I do understand about `js` is that it won't execute until that event is fired off in some way.

knowing this (and with a bit of application testing) in `atom-python-run.js`, we could do some thing like this.

```
tty = spawn.tty({
    'pause': config.pause,
    'pipeFile': config.pipeFile,
    'pipePath': config.pipePath,
    'log': config.consoleLog,
    'args': args,
    'options': {
        cwd: info.dir,
        detached: true
    }
});

if (null == tty) {
    console.log('atom-python-run: ExceptionError: `terminal` refused to spawn a `tty` instance');
    return;
}

(function onError(error, shellName) {
    atom.notifications.addError('There was a problem opening \''
        + shellName + '\'. If your computer doesn\'t have \'' + shellName
        + '\' installed, you can set your own terminal on the package\'s ' +
        'Settings.');
})(error, spawn.object.shell);

tty.unref();
```

You can always apply it your way. Again, it's just about separating concerns.

Comment (xovertheyearsx) [reply lib/terminal.js]: I was thinking something like this, just as an example.

Starting at line 95 in `atom-python-run.js`:
```javascript
tty = spawn.tty({
    'pause': config.pause,
    'pipeFile': config.pipeFile,
    'pipePath': config.pipePath,
    'log': config.consoleLog,
    'args': args,
    'options': {
        cwd: info.dir,
        detached: true
    }
});

try {
    tty.on('error', function (error) {
      atom.notifications.addError(`There was a problem opening ` +
      `'${spawn.object.shell}'. If your computer doesn't have '${spawn.object.shell}'` +
      `installed, you can set your own terminal on the package's Settings.`);
    });

    tty.unref();
} catch(e) {
    atom.notifications.addError(`atom-python-run: ExceptionError: 'terminal' refused to spawn a 'tty' instance: ${e}`);
    return;
}
```
